[build]
  publish = "."

[[redirects]]
  from = "/getting-started"
  to = "/getting-started.html"
  status = 200

[[redirects]]
  from = "/invite"
  to = "/invite.html"
  status = 200

[[redirects]]
  from = "/billing"
  to = "/billing.html"
  status = 200

[[redirects]]
  from = "/teams"
  to = "/teams.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
